title: "Non-Parametric Derivative Estimation Research"
description: "A comprehensive review of research papers on non-parametric derivative estimation using penalized B-splines"
author: "Christopher Odoom"
baseurl: "/Literature_review"
url: "https://christopherodoom.github.io"
github_username: christopherodoom
google_analytics: 
contact_email: 

theme: jekyll-theme-minimal

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - .env
  - .env.example
  - .env.local
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore
  - .git
  - derivative_estimation.ipynb